### ISSUE TITLE
BME680 compensation algorithms

### ISSUE THREAD

**Issue by gschorcht** [kriswiner/BME680#3]
Hi Kris,

where did you find the compensation algorithms for temperature, pressure and humidity. In the BME680 datasheet there is only described the compensation algorithm for gas. The algorithms described in the datasheets of BME280 and BMP280 differs slightly.

Regards
Gunar

**Comment by kriswiner** [comment]
Must have been a previous data sheet. I was working on this more than a
year ago and don't really remember.
